//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI_Test2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GUI_Test2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap check {
            get {
                object obj = ResourceManager.GetObject("check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;SFML\Graphics.hpp&gt;
        ///#include &lt;iostream&gt;
        ///
        ///#include &lt;SFML/Audio.hpp&gt;
        ///#include &lt;string&gt;
        ///#include &lt;fstream&gt;
        ///#include &lt;ctime&gt;
        ///#include &lt;cstdlib&gt;
        ///#include &lt;Windows.h&gt;
        ///#include &lt;sstream&gt;
        ///#include &quot;Path.h&quot;
        ///#include &quot;PathGroup.h&quot;
        ///#include &quot;Character.h&quot;
        ///#include &quot;Requirements.h&quot;
        ///#include &quot;Game.h&quot;
        ///#include &quot;Player.h&quot;
        ///#include &quot;AttributeMap.h&quot;
        ///#include &quot;Hub.h&quot;
        ///#include &quot;Interface.h&quot;
        ///#include &quot;Impact.h&quot;
        ///#include &quot;MainMenu.h&quot;
        ///
        ///static float VIEW_HEIGHT = 1080.0f;
        ///            static float VI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cookieCutterGame {
            get {
                return ResourceManager.GetString("cookieCutterGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap defaultCharacter {
            get {
                object obj = ResourceManager.GetObject("defaultCharacter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sf::RenderWindow window(sf::VideoMode::getDesktopMode(), &quot;Game Window&quot;, sf::Style::None);
        ///        sf::View view(sf::Vector2f(0.0f, 0.0f), sf::Vector2f(VIEW_WIDTH, VIEW_HEIGHT));
        ///        window.setView(view);
        ///        window.setFramerateLimit(60);
        ///
        ///       
        ///        (*game).play(window, view);
        ///}.
        /// </summary>
        internal static string defaultFooter {
            get {
                return ResourceManager.GetString("defaultFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;Game.h&quot;
        ///#include &quot;Path.h&quot;
        ///#include &quot;PathGroup.h&quot;
        ///#include &quot;Hub.h&quot;
        ///#include &quot;Requirements.h&quot;
        ///#include &quot;Impact.h&quot;
        ///#include &quot;Character.h&quot;
        ///#include &lt;iostream&gt;
        ///
        ///static float VIEW_HEIGHT = 1080.0f;
        ///static float VIEW_WIDTH = 1920.0f;
        ///
        ///int main() {
        ///.
        /// </summary>
        internal static string defaultHeader {
            get {
                return ResourceManager.GetString("defaultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap defaultHub {
            get {
                object obj = ResourceManager.GetObject("defaultHub", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap defaultPath {
            get {
                object obj = ResourceManager.GetObject("defaultPath", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphic {
            get {
                object obj = ResourceManager.GetObject("graphic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphic2 {
            get {
                object obj = ResourceManager.GetObject("graphic2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoNavigableSelected {
            get {
                object obj = ResourceManager.GetObject("NoNavigableSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PathGroup {
            get {
                object obj = ResourceManager.GetObject("PathGroup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap redx {
            get {
                object obj = ResourceManager.GetObject("redx", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
